I am going to start by experimenting with pandas

In [2]:
import pandas as pd

df = pd.read_csv("../data/raw/books.csv") # CSV -> DataFrame

In [3]:
#Trying out pandas methods
df.head() # Show the first 5 rows of the DataFrame

,title,category,description,image_url,image_path
0,Soumission,Fiction,"Dans une France assez proche de la nôtre, un h...",https://books.toscrape.com/media/cache/ee/cf/e...,images/soumission_998.jpg
1,Private Paris (Private #10),Fiction,Paris is burning--and only Private's Jack Morg...,https://books.toscrape.com/media/cache/05/87/0...,images/private-paris-private-10_958.jpg
2,"We Love You, Charlie Freeman",Fiction,"The Freeman family--Charles, Laurel, and their...",https://books.toscrape.com/media/cache/87/a2/8...,images/we-love-you-charlie-freeman_954.jpg
3,Thirst,Fiction,"On a searing summer Friday, Eddie Chapman has ...",https://books.toscrape.com/media/cache/8c/54/8...,images/thirst_946.jpg
4,The Murder That Never Was (Forensic Instincts #5),Fiction,"Given the opportunity, would you assume someon...",https://books.toscrape.com/media/cache/29/e0/2...,images/the-murder-that-never-was-forensic-inst...

From df.head() we see that we have the columns we wanted

In [4]:
df.info() # Show information about the DataFrame, including column names, data types, and non-null counts

<class 'pandas.DataFrame'>
RangeIndex: 175 entries, 0 to 174
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   title        175 non-null    str
 1   category     175 non-null    str
 2   description  175 non-null    str
 3   image_url    175 non-null    str
 4   image_path   175 non-null    str
dtypes: str(5)
memory usage: 7.0 KB

In [5]:
df.shape # Show the number of rows and columns in the DataFrame

(175, 5)

In [6]:
df["category"].value_counts() # Show the count of unique values in the "category" column

category
Nonfiction    110
Fiction        65
Name: count, dtype: int64

Here we can see that we have all the books we wanted from both categories

In [7]:
df.loc[0, "description"] # Show the description of the first book (row 0)

'Dans une France assez proche de la nôtre, un homme s’engage dans la carrière universitaire. Peu motivé par l’enseignement, il s’attend à une vie ennuyeuse mais calme, protégée des grands drames historiques. Cependant les forces en jeu dans le pays ont fissuré le système politique jusqu’à provoquer son effondrement. Cette implosion sans soubresauts, sans vraie révolution, s Dans une France assez proche de la nôtre, un homme s’engage dans la carrière universitaire. Peu motivé par l’enseignement, il s’attend à une vie ennuyeuse mais calme, protégée des grands drames historiques. Cependant les forces en jeu dans le pays ont fissuré le système politique jusqu’à provoquer son effondrement. Cette implosion sans soubresauts, sans vraie révolution, se développe comme un mauvais rêve.Le talent de l’auteur, sa force visionnaire nous entraînent sur un terrain ambigu et glissant ; son regard sur notre civilisation vieillissante fait coexister dans ce roman les intuitions poétiques, les effets comiques, une mélancolie fataliste.Ce livre est une saisissante fable politique et morale. ...more'

Im going to look for some books that have a description in english to spare my eyes. I am going to start by looking at 5 and see if i notice anything wrong with the data.

In [8]:
for i in range(11):
    print(df.loc[i, "description"])

Dans une France assez proche de la nôtre, un homme s’engage dans la carrière universitaire. Peu motivé par l’enseignement, il s’attend à une vie ennuyeuse mais calme, protégée des grands drames historiques. Cependant les forces en jeu dans le pays ont fissuré le système politique jusqu’à provoquer son effondrement. Cette implosion sans soubresauts, sans vraie révolution, s Dans une France assez proche de la nôtre, un homme s’engage dans la carrière universitaire. Peu motivé par l’enseignement, il s’attend à une vie ennuyeuse mais calme, protégée des grands drames historiques. Cependant les forces en jeu dans le pays ont fissuré le système politique jusqu’à provoquer son effondrement. Cette implosion sans soubresauts, sans vraie révolution, se développe comme un mauvais rêve.Le talent de l’auteur, sa force visionnaire nous entraînent sur un terrain ambigu et glissant ; son regard sur notre civilisation vieillissante fait coexister dans ce roman les intuitions poétiques, les effets comiques, une mélancolie fataliste.Ce livre est une saisissante fable politique et morale. ...more
Paris is burning--and only Private's Jack Morgan can put out the fire.When Jack Morgan stops by Private's Paris office, he envisions a quick hello during an otherwise relaxing trip filled with fine food and sightseeing. But Jack is quickly pressed into duty after a call from his client Sherman Wilkerson, asking Jack to track down his young granddaughter who is on the run f Paris is burning--and only Private's Jack Morgan can put out the fire.When Jack Morgan stops by Private's Paris office, he envisions a quick hello during an otherwise relaxing trip filled with fine food and sightseeing. But Jack is quickly pressed into duty after a call from his client Sherman Wilkerson, asking Jack to track down his young granddaughter who is on the run from a brutal drug dealer.Before Jack can locate her, several members of France's cultural elite are found dead--murdered in stunning, symbolic fashion. The only link between the crimes is a mysterious graffiti tag. As religious and ethnic tensions simmer in the City of Lights, only Jack and his Private team can connect the dots before the smoldering powder keg explodes. ...more
The Freeman family--Charles, Laurel, and their daughters, teenage Charlotte and nine-year-old Callie--have been invited to the Toneybee Institute in rural Massachusetts to participate in a research experiment. They will live in an apartment on campus with Charlie, a young chimp abandoned by his mother. The Freemans were selected for the experiment because they know sign la The Freeman family--Charles, Laurel, and their daughters, teenage Charlotte and nine-year-old Callie--have been invited to the Toneybee Institute in rural Massachusetts to participate in a research experiment. They will live in an apartment on campus with Charlie, a young chimp abandoned by his mother. The Freemans were selected for the experiment because they know sign language; they are supposed to teach it to Charlie and welcome him as a member of their family. Isolated in their new, nearly all-white community not just by their race but by their strange living situation, the Freemans come undone. And when Charlotte discovers the truth about the Institute’s history of questionable studies, the secrets of the past begin to invade the present. The power of this novel resides in Kaitlyn Greenidge’s undeniable storytelling talents. What appears to be a story of mothers and daughters, of sisterhood put to the test, of adolescent love and grown-up misconduct, and of history’s long reach, becomes a provocative and compelling exploration of America’s failure to find a language to talk about race. ...more
On a searing summer Friday, Eddie Chapman has been stuck for hours in a traffic jam. There are accidents along the highway, but ambulances and police are conspicuously absent. When he decides to abandon his car and run home, he sees that the trees along the edge of a stream have been burnt, and the water in the streambed is gone. Something is very wrong.When he arrives hom On a searing summer Friday, Eddie Chapman has been stuck for hours in a traffic jam. There are accidents along the highway, but ambulances and police are conspicuously absent. When he decides to abandon his car and run home, he sees that the trees along the edge of a stream have been burnt, and the water in the streambed is gone. Something is very wrong.When he arrives home, the power is out and there is no running water. The pipes everywhere, it seems, have gone dry. Eddie and his wife, Laura, find themselves thrust together with their neighbors while a sense of unease thickens in the stifling night air. Thirst takes place in the immediate aftermath of a mysterious disaster--the Chapmans and their neighbors suffer the effects of the heat, their thirst, and the terrifying realization that no one is coming to help. As violence rips through the community, Eddie and Laura are forced to recall secrets from their past and question their present humanity. In crisp and convincing prose, Ben Warner compels readers to do the same. What might you do to survive? ...more
Given the opportunity, would you assume someone else's identity and leave your old life behind? A serendipitous crossing of paths between Lisa Barnes, a down-on-her-luck job seeker, and Julie Forman, a personal trainer to an Olympic hopeful, forever changes the course of both women's lives. One winds up dead and the other finds herself a fugitive, hiding behind one lie aft Given the opportunity, would you assume someone else's identity and leave your old life behind? A serendipitous crossing of paths between Lisa Barnes, a down-on-her-luck job seeker, and Julie Forman, a personal trainer to an Olympic hopeful, forever changes the course of both women's lives. One winds up dead and the other finds herself a fugitive, hiding behind one lie after another as a cold-blooded killer methodically hunts her. Desperately trying to stay alive, the terrified woman enlists the help of Forensic Instincts, a rogue investigative team that clandestinely operates in the gray area between legal and illegal. Safeguarding their client's deception, Forensic Instincts digs into dangerous territory as they try to find out who's after their client and why. Meanwhile, bodies are piling up in Chicago, New Jersey, and Vermont as a megalomaniacal genius will stop at nothing to eradicate anyone who threatens the success of his medical breakthrough. With an unhinged client and a monstrous criminal enterprise as its adversary, Forensic Instincts is forced into uncharted territory to protect their client and save one of their own from becoming the next corpse. Forensic Instincts is an unorthodox, criminal investigative team that carefully navigates the fine line between legal and illegal. The team consists of a behaviorist, a former Navy SEAL, a techo-wiz, an intuitive, a pickpocket, a retired FBI agent, and a human scent evidence dog." ...more
“In one sentence, Ms. Prentiss captures a sense of intoxication and possibility that six seasons of voice-overs from Sarah Jessica Parker never could…Ms. Prentiss concludes her novel on a note that’s both ethereal and brutally realistic. She cauterizes wounds, but they’re still visible and bare. But for her characters—for this promising author—it’s enough.” —The New York T “In one sentence, Ms. Prentiss captures a sense of intoxication and possibility that six seasons of voice-overs from Sarah Jessica Parker never could…Ms. Prentiss concludes her novel on a note that’s both ethereal and brutally realistic. She cauterizes wounds, but they’re still visible and bare. But for her characters—for this promising author—it’s enough.” —The New York Times“An intoxicating Manhattan fairy tale…As affecting as it is absorbing. A thrilling debut.” —Kirkus Reviews (starred review) “A vital, sensuous, edgy, and suspenseful tale of longing, rage, fear, compulsion, and love.” —Booklist (starred review) An intoxicating and transcendent debut novel that follows a critic, an artist, and a desirous, determined young woman as they find their way—and ultimately collide—amid the ever-evolving New York City art scene of the 1980s.Welcome to SoHo at the onset of the eighties: a gritty, not-yet-gentrified playground for artists and writers looking to make it in the big city. Among them: James Bennett, a synesthetic art critic for The New York Times whose unlikely condition enables him to describe art in profound, magical ways, and Raul Engales, an exiled Argentinian painter running from his past and the Dirty War that has enveloped his country. As the two men ascend in the downtown arts scene, dual tragedies strike, and each is faced with a loss that acutely affects his relationship to life and to art. It is not until they are inadvertently brought together by Lucy Olliason—a small town beauty and Raul’s muse—and a young orphan boy sent mysteriously from Buenos Aires, that James and Raul are able to rediscover some semblance of what they’ve lost.As inventive as Jennifer Egan's A Visit From The Goon Squad and as sweeping as Meg Wolitzer's The Interestings, Tuesday Nights in 1980 boldly renders a complex moment when the meaning and nature of art is being all but upended, and New York City as a whole is reinventing itself. In risk-taking prose that is as powerful as it is playful, Molly Prentiss deftly explores the need for beauty, community, creation, and love in an ever-changing urban landscape. ...more
An irresistible, deftly observed novel about the secrets, joys, and jealousies that rise to the surface over the course of an American family’s two-week stay in Mallorca. For the Posts, a two-week trip to the Balearic island of Mallorca with their extended family and friends is a celebration: Franny and Jim are observing their thirty-fifth wedding anniversary, and their da An irresistible, deftly observed novel about the secrets, joys, and jealousies that rise to the surface over the course of an American family’s two-week stay in Mallorca. For the Posts, a two-week trip to the Balearic island of Mallorca with their extended family and friends is a celebration: Franny and Jim are observing their thirty-fifth wedding anniversary, and their daughter, Sylvia, has graduated from high school. The sunlit island, its mountains and beaches, its tapas and tennis courts, also promise an escape from the tensions simmering at home in Manhattan. But all does not go according to plan: over the course of the vacation, secrets come to light, old and new humiliations are experienced, childhood rivalries resurface, and ancient wounds are exacerbated. This is a story of the sides of ourselves that we choose to show and those we try to conceal, of the ways we tear each other down and build each other up again, and the bonds that ultimately hold us together. With wry humor and tremendous heart, Emma Straub delivers a richly satisfying story of a family in the midst of a maelstrom of change, emerging irrevocably altered yet whole. ...more
In a world beset by amassing forces of darkness, one organization—the Regional Office—and its coterie of super-powered female assassins protects the globe from annihilation. At its helm, the mysterious Oyemi and her oracles seek out new recruits and root out evil plots. Then a prophecy suggests that someone from inside might bring about its downfall. And now, the Regional In a world beset by amassing forces of darkness, one organization—the Regional Office—and its coterie of super-powered female assassins protects the globe from annihilation. At its helm, the mysterious Oyemi and her oracles seek out new recruits and root out evil plots. Then a prophecy suggests that someone from inside might bring about its downfall. And now, the Regional Office is under attack.   Recruited by a defector from within, Rose is a young assassin leading the attack, eager to stretch into her powers and prove herself on her first mission. Defending the Regional Office is Sarah—who may or may not have a mechanical arm—fiercely devoted to the organization that took her in as a young woman in the wake of her mother’s sudden disappearance. On the day that the Regional Office is attacked, Rose’s and Sarah’s stories will overlap, their lives will collide, and the world as they know it just might end. ...more
A masterful, intensely suspenseful novel about a reader whose obsession with a reclusive writer goes far too far—a book about the power of storytelling, starring the same trio of unlikely and winning heroes King introduced in Mr. Mercedes“Wake up, genius.” So begins King’s instantly riveting story about a vengeful reader. The genius is John Rothstein, an iconic author who A masterful, intensely suspenseful novel about a reader whose obsession with a reclusive writer goes far too far—a book about the power of storytelling, starring the same trio of unlikely and winning heroes King introduced in Mr. Mercedes“Wake up, genius.” So begins King’s instantly riveting story about a vengeful reader. The genius is John Rothstein, an iconic author who created a famous character, Jimmy Gold, but who hasn’t published a book for decades. Morris Bellamy is livid, not just because Rothstein has stopped providing books, but because the nonconformist Jimmy Gold has sold out for a career in advertising. Morris kills Rothstein and empties his safe of cash, yes, but the real treasure is a trove of notebooks containing at least one more Gold novel.Morris hides the money and the notebooks, and then he is locked away for another crime. Decades later, a boy named Pete Saubers finds the treasure, and now it is Pete and his family that Bill Hodges, Holly Gibney, and Jerome Robinson must rescue from the ever-more deranged and vengeful Morris when he’s released from prison after thirty-five years.Not since Misery has King played with the notion of a reader whose obsession with a writer gets dangerous. Finders Keepers is spectacular, heart-pounding suspense, but it is also King writing about how literature shapes a life—for good, for bad, forever. ...more
In this fable, the first man on earth to count the hours becomes Father Time. The inventor of the world's first clock is punished for trying to measure God's greatest gift. He is banished to a cave for centuries and forced to listen to the voices of all who come after him seeking more days, more years. Eventually, with his soul nearly broken, Father Time is granted his fre In this fable, the first man on earth to count the hours becomes Father Time. The inventor of the world's first clock is punished for trying to measure God's greatest gift. He is banished to a cave for centuries and forced to listen to the voices of all who come after him seeking more days, more years. Eventually, with his soul nearly broken, Father Time is granted his freedom, along with a magical hourglass and a mission: a chance to redeem himself by teaching two earthly people the true meaning of time.He returns to our world - now dominated by the hour-counting he so innocently began - and commences a journey with two unlikely partners: one a teenage girl who is about to give up on life, the other a wealthy old businessman who wants to live forever. To save himself, he must save them both. And stop the world to do so. ...more
Provocative, haunting, and indelible, Colm Tóibín’s portrait of Mary presents her as a solitary older woman still seeking to understand the events that become the narrative of the New Testament and the foundation of Christianity.In the ancient town of Ephesus, Mary lives alone, years after her son's crucifixion. She has no interest in collaborating with the authors of the Provocative, haunting, and indelible, Colm Tóibín’s portrait of Mary presents her as a solitary older woman still seeking to understand the events that become the narrative of the New Testament and the foundation of Christianity.In the ancient town of Ephesus, Mary lives alone, years after her son's crucifixion. She has no interest in collaborating with the authors of the Gospel—her keepers, who provide her with food and shelter and visit her regularly. She does not agree that her son is the Son of God; nor that his death was “worth it;” nor that the “group of misfits he gathered around him, men who could not look a woman in the eye,” were holy disciples. Mary judges herself ruthlessly (she did not stay at the foot of the Cross until her son died—she fled, to save herself), and is equally harsh on her judgment of others. This woman who we know from centuries of paintings and scripture as the docile, loving, silent, long-suffering, obedient, worshipful mother of Christ becomes, in Toibin’s searing evocation, a tragic heroine with the relentless eloquence of Electra or Medea or Antigone. This tour de force of imagination and language is a portrait so vivid and convincing that our image of Mary will be forever transformed. ...more

Seems like it was only the first book that was in french. In that case im going to examine books 2,3,4,5,6

In [9]:
for i in range(1,7):
    print(df.loc[i, "title"])
    print(df.loc[i, "category"])
    print(df.loc[i, "description"])
    print(df.loc[i, "image_path"])

Private Paris (Private #10)
Fiction
Paris is burning--and only Private's Jack Morgan can put out the fire.When Jack Morgan stops by Private's Paris office, he envisions a quick hello during an otherwise relaxing trip filled with fine food and sightseeing. But Jack is quickly pressed into duty after a call from his client Sherman Wilkerson, asking Jack to track down his young granddaughter who is on the run f Paris is burning--and only Private's Jack Morgan can put out the fire.When Jack Morgan stops by Private's Paris office, he envisions a quick hello during an otherwise relaxing trip filled with fine food and sightseeing. But Jack is quickly pressed into duty after a call from his client Sherman Wilkerson, asking Jack to track down his young granddaughter who is on the run from a brutal drug dealer.Before Jack can locate her, several members of France's cultural elite are found dead--murdered in stunning, symbolic fashion. The only link between the crimes is a mysterious graffiti tag. As religious and ethnic tensions simmer in the City of Lights, only Jack and his Private team can connect the dots before the smoldering powder keg explodes. ...more
images/private-paris-private-10_958.jpg
We Love You, Charlie Freeman
Fiction
The Freeman family--Charles, Laurel, and their daughters, teenage Charlotte and nine-year-old Callie--have been invited to the Toneybee Institute in rural Massachusetts to participate in a research experiment. They will live in an apartment on campus with Charlie, a young chimp abandoned by his mother. The Freemans were selected for the experiment because they know sign la The Freeman family--Charles, Laurel, and their daughters, teenage Charlotte and nine-year-old Callie--have been invited to the Toneybee Institute in rural Massachusetts to participate in a research experiment. They will live in an apartment on campus with Charlie, a young chimp abandoned by his mother. The Freemans were selected for the experiment because they know sign language; they are supposed to teach it to Charlie and welcome him as a member of their family. Isolated in their new, nearly all-white community not just by their race but by their strange living situation, the Freemans come undone. And when Charlotte discovers the truth about the Institute’s history of questionable studies, the secrets of the past begin to invade the present. The power of this novel resides in Kaitlyn Greenidge’s undeniable storytelling talents. What appears to be a story of mothers and daughters, of sisterhood put to the test, of adolescent love and grown-up misconduct, and of history’s long reach, becomes a provocative and compelling exploration of America’s failure to find a language to talk about race. ...more
images/we-love-you-charlie-freeman_954.jpg
Thirst
Fiction
On a searing summer Friday, Eddie Chapman has been stuck for hours in a traffic jam. There are accidents along the highway, but ambulances and police are conspicuously absent. When he decides to abandon his car and run home, he sees that the trees along the edge of a stream have been burnt, and the water in the streambed is gone. Something is very wrong.When he arrives hom On a searing summer Friday, Eddie Chapman has been stuck for hours in a traffic jam. There are accidents along the highway, but ambulances and police are conspicuously absent. When he decides to abandon his car and run home, he sees that the trees along the edge of a stream have been burnt, and the water in the streambed is gone. Something is very wrong.When he arrives home, the power is out and there is no running water. The pipes everywhere, it seems, have gone dry. Eddie and his wife, Laura, find themselves thrust together with their neighbors while a sense of unease thickens in the stifling night air. Thirst takes place in the immediate aftermath of a mysterious disaster--the Chapmans and their neighbors suffer the effects of the heat, their thirst, and the terrifying realization that no one is coming to help. As violence rips through the community, Eddie and Laura are forced to recall secrets from their past and question their present humanity. In crisp and convincing prose, Ben Warner compels readers to do the same. What might you do to survive? ...more
images/thirst_946.jpg
The Murder That Never Was (Forensic Instincts #5)
Fiction
Given the opportunity, would you assume someone else's identity and leave your old life behind? A serendipitous crossing of paths between Lisa Barnes, a down-on-her-luck job seeker, and Julie Forman, a personal trainer to an Olympic hopeful, forever changes the course of both women's lives. One winds up dead and the other finds herself a fugitive, hiding behind one lie aft Given the opportunity, would you assume someone else's identity and leave your old life behind? A serendipitous crossing of paths between Lisa Barnes, a down-on-her-luck job seeker, and Julie Forman, a personal trainer to an Olympic hopeful, forever changes the course of both women's lives. One winds up dead and the other finds herself a fugitive, hiding behind one lie after another as a cold-blooded killer methodically hunts her. Desperately trying to stay alive, the terrified woman enlists the help of Forensic Instincts, a rogue investigative team that clandestinely operates in the gray area between legal and illegal. Safeguarding their client's deception, Forensic Instincts digs into dangerous territory as they try to find out who's after their client and why. Meanwhile, bodies are piling up in Chicago, New Jersey, and Vermont as a megalomaniacal genius will stop at nothing to eradicate anyone who threatens the success of his medical breakthrough. With an unhinged client and a monstrous criminal enterprise as its adversary, Forensic Instincts is forced into uncharted territory to protect their client and save one of their own from becoming the next corpse. Forensic Instincts is an unorthodox, criminal investigative team that carefully navigates the fine line between legal and illegal. The team consists of a behaviorist, a former Navy SEAL, a techo-wiz, an intuitive, a pickpocket, a retired FBI agent, and a human scent evidence dog." ...more
images/the-murder-that-never-was-forensic-instincts-5_939.jpg
Tuesday Nights in 1980
Fiction
“In one sentence, Ms. Prentiss captures a sense of intoxication and possibility that six seasons of voice-overs from Sarah Jessica Parker never could…Ms. Prentiss concludes her novel on a note that’s both ethereal and brutally realistic. She cauterizes wounds, but they’re still visible and bare. But for her characters—for this promising author—it’s enough.” —The New York T “In one sentence, Ms. Prentiss captures a sense of intoxication and possibility that six seasons of voice-overs from Sarah Jessica Parker never could…Ms. Prentiss concludes her novel on a note that’s both ethereal and brutally realistic. She cauterizes wounds, but they’re still visible and bare. But for her characters—for this promising author—it’s enough.” —The New York Times“An intoxicating Manhattan fairy tale…As affecting as it is absorbing. A thrilling debut.” —Kirkus Reviews (starred review) “A vital, sensuous, edgy, and suspenseful tale of longing, rage, fear, compulsion, and love.” —Booklist (starred review) An intoxicating and transcendent debut novel that follows a critic, an artist, and a desirous, determined young woman as they find their way—and ultimately collide—amid the ever-evolving New York City art scene of the 1980s.Welcome to SoHo at the onset of the eighties: a gritty, not-yet-gentrified playground for artists and writers looking to make it in the big city. Among them: James Bennett, a synesthetic art critic for The New York Times whose unlikely condition enables him to describe art in profound, magical ways, and Raul Engales, an exiled Argentinian painter running from his past and the Dirty War that has enveloped his country. As the two men ascend in the downtown arts scene, dual tragedies strike, and each is faced with a loss that acutely affects his relationship to life and to art. It is not until they are inadvertently brought together by Lucy Olliason—a small town beauty and Raul’s muse—and a young orphan boy sent mysteriously from Buenos Aires, that James and Raul are able to rediscover some semblance of what they’ve lost.As inventive as Jennifer Egan's A Visit From The Goon Squad and as sweeping as Meg Wolitzer's The Interestings, Tuesday Nights in 1980 boldly renders a complex moment when the meaning and nature of art is being all but upended, and New York City as a whole is reinventing itself. In risk-taking prose that is as powerful as it is playful, Molly Prentiss deftly explores the need for beauty, community, creation, and love in an ever-changing urban landscape. ...more
images/tuesday-nights-in-1980_870.jpg
The Vacationers
Fiction
An irresistible, deftly observed novel about the secrets, joys, and jealousies that rise to the surface over the course of an American family’s two-week stay in Mallorca. For the Posts, a two-week trip to the Balearic island of Mallorca with their extended family and friends is a celebration: Franny and Jim are observing their thirty-fifth wedding anniversary, and their da An irresistible, deftly observed novel about the secrets, joys, and jealousies that rise to the surface over the course of an American family’s two-week stay in Mallorca. For the Posts, a two-week trip to the Balearic island of Mallorca with their extended family and friends is a celebration: Franny and Jim are observing their thirty-fifth wedding anniversary, and their daughter, Sylvia, has graduated from high school. The sunlit island, its mountains and beaches, its tapas and tennis courts, also promise an escape from the tensions simmering at home in Manhattan. But all does not go according to plan: over the course of the vacation, secrets come to light, old and new humiliations are experienced, childhood rivalries resurface, and ancient wounds are exacerbated. This is a story of the sides of ourselves that we choose to show and those we try to conceal, of the ways we tear each other down and build each other up again, and the bonds that ultimately hold us together. With wry humor and tremendous heart, Emma Straub delivers a richly satisfying story of a family in the midst of a maelstrom of change, emerging irrevocably altered yet whole. ...more
images/the-vacationers_863.jpg

Looking at the descriptions we see that some descriptions begin with a teaser, this teaser then appears again in the description. Some descriptions also end with ...more. We need to clean both of this things up.

i want to create a function that: 
1. remove ...more at the end
2. Looks at the first sentences in the description and checks if it appears again
3. Keeps only the text from that point
4. Returns the text

For 
1. I want to try using str.removesuffix()
2. I believe i can use str.find(sub, start)
3. str.strip

In [10]:
test_string = df.loc[0, "description"]
test_string = test_string.removesuffix("...more")
print(test_string)
test_string_2 = "This is just a random string that I am using to test the .removesuffix() method. It does not have a suffix that I want to remove."
test_string_2 = test_string_2.removesuffix("...more")
print(test_string_2)

Dans une France assez proche de la nôtre, un homme s’engage dans la carrière universitaire. Peu motivé par l’enseignement, il s’attend à une vie ennuyeuse mais calme, protégée des grands drames historiques. Cependant les forces en jeu dans le pays ont fissuré le système politique jusqu’à provoquer son effondrement. Cette implosion sans soubresauts, sans vraie révolution, s Dans une France assez proche de la nôtre, un homme s’engage dans la carrière universitaire. Peu motivé par l’enseignement, il s’attend à une vie ennuyeuse mais calme, protégée des grands drames historiques. Cependant les forces en jeu dans le pays ont fissuré le système politique jusqu’à provoquer son effondrement. Cette implosion sans soubresauts, sans vraie révolution, se développe comme un mauvais rêve.Le talent de l’auteur, sa force visionnaire nous entraînent sur un terrain ambigu et glissant ; son regard sur notre civilisation vieillissante fait coexister dans ce roman les intuitions poétiques, les effets comiques, une mélancolie fataliste.Ce livre est une saisissante fable politique et morale.
This is just a random string that I am using to test the .removesuffix() method. It does not have a suffix that I want to remove.

1. Done 
Onto 2.

In [11]:
sample = "Once upon a time there was a dra Once upon a time there was a dragon who loved books. ...more"

print(sample[:20])            # what are the first 20 characters?
print(sample.find("Once"))    # where is the first "Once"?
print(sample.find("Once", 1)) # where is the second one?

print(test_string[:20])            # what are the first 20 characters?
print(test_string.find(test_string[:20]))    
print(test_string.find(test_string[:20], 1)) # Where does the 20 characters repeat?

Once upon a time the
0
33
Dans une France asse
0
376

In [12]:
print(test_string)
test_string = test_string[test_string.find(test_string[:20], 1):] # Removes the sentence before the second occurrence of the first 20 characters
print(test_string) 
sample = "This is a sample string that I am using to test the .find() method. I want to know what happens if it does not find the substring that I am looking for."
sample = sample[sample.find(sample[:20], 1):] 
print(sample)

Dans une France assez proche de la nôtre, un homme s’engage dans la carrière universitaire. Peu motivé par l’enseignement, il s’attend à une vie ennuyeuse mais calme, protégée des grands drames historiques. Cependant les forces en jeu dans le pays ont fissuré le système politique jusqu’à provoquer son effondrement. Cette implosion sans soubresauts, sans vraie révolution, s Dans une France assez proche de la nôtre, un homme s’engage dans la carrière universitaire. Peu motivé par l’enseignement, il s’attend à une vie ennuyeuse mais calme, protégée des grands drames historiques. Cependant les forces en jeu dans le pays ont fissuré le système politique jusqu’à provoquer son effondrement. Cette implosion sans soubresauts, sans vraie révolution, se développe comme un mauvais rêve.Le talent de l’auteur, sa force visionnaire nous entraînent sur un terrain ambigu et glissant ; son regard sur notre civilisation vieillissante fait coexister dans ce roman les intuitions poétiques, les effets comiques, une mélancolie fataliste.Ce livre est une saisissante fable politique et morale.
Dans une France assez proche de la nôtre, un homme s’engage dans la carrière universitaire. Peu motivé par l’enseignement, il s’attend à une vie ennuyeuse mais calme, protégée des grands drames historiques. Cependant les forces en jeu dans le pays ont fissuré le système politique jusqu’à provoquer son effondrement. Cette implosion sans soubresauts, sans vraie révolution, se développe comme un mauvais rêve.Le talent de l’auteur, sa force visionnaire nous entraînent sur un terrain ambigu et glissant ; son regard sur notre civilisation vieillissante fait coexister dans ce roman les intuitions poétiques, les effets comiques, une mélancolie fataliste.Ce livre est une saisissante fable politique et morale.
.

Something is a bit wrong cause if i run it more than once it keeps on removing from the string. I need to fix that

In [13]:
sample = "This is a sample string that I am using to test the .find() method. I want to know what happens if it does not find the substring that I am looking for."
index = sample.find(sample[:20], 1)
print(index)
sample = sample[index:] if index != -1 else sample
print(sample)
test_string = df.loc[0, "description"]
index2 = test_string.find(test_string[:20], 1)
print(index2)
test_string = test_string[index2:] if index2 != -1 else test_string
print(test_string)
index2 = test_string.find(test_string[:20], 1)
print(index2)
test_string = test_string[index2:] if index2 != -1 else test_string
print(test_string)

-1
This is a sample string that I am using to test the .find() method. I want to know what happens if it does not find the substring that I am looking for.
376
Dans une France assez proche de la nôtre, un homme s’engage dans la carrière universitaire. Peu motivé par l’enseignement, il s’attend à une vie ennuyeuse mais calme, protégée des grands drames historiques. Cependant les forces en jeu dans le pays ont fissuré le système politique jusqu’à provoquer son effondrement. Cette implosion sans soubresauts, sans vraie révolution, se développe comme un mauvais rêve.Le talent de l’auteur, sa force visionnaire nous entraînent sur un terrain ambigu et glissant ; son regard sur notre civilisation vieillissante fait coexister dans ce roman les intuitions poétiques, les effets comiques, une mélancolie fataliste.Ce livre est une saisissante fable politique et morale. ...more
-1
Dans une France assez proche de la nôtre, un homme s’engage dans la carrière universitaire. Peu motivé par l’enseignement, il s’attend à une vie ennuyeuse mais calme, protégée des grands drames historiques. Cependant les forces en jeu dans le pays ont fissuré le système politique jusqu’à provoquer son effondrement. Cette implosion sans soubresauts, sans vraie révolution, se développe comme un mauvais rêve.Le talent de l’auteur, sa force visionnaire nous entraînent sur un terrain ambigu et glissant ; son regard sur notre civilisation vieillissante fait coexister dans ce roman les intuitions poétiques, les effets comiques, une mélancolie fataliste.Ce livre est une saisissante fable politique et morale. ...more

Now i have everything i need to clean my description. Lets write a function for it

In [14]:
def clean_description(description):
    description = description.removesuffix("...more")
    description = description.strip() 
    
    teaser_end = description.find(description[:20], 1)
    # Only cut if the repeat is where a teaser ends (always at 372-377 in this data).
    if 350 <= teaser_end <= 400:
        description = description[teaser_end:]

    description = description.replace("\xad", "") # Remove soft hyphens (invisible characters inside words)
    description = " ".join(description.split())  # Turn non-breaking spaces and double spaces into one normal space

    return description

clean_description(df.loc[0, "description"])

'Dans une France assez proche de la nôtre, un homme s’engage dans la carrière universitaire. Peu motivé par l’enseignement, il s’attend à une vie ennuyeuse mais calme, protégée des grands drames historiques. Cependant les forces en jeu dans le pays ont fissuré le système politique jusqu’à provoquer son effondrement. Cette implosion sans soubresauts, sans vraie révolution, se développe comme un mauvais rêve.Le talent de l’auteur, sa force visionnaire nous entraînent sur un terrain ambigu et glissant ; son regard sur notre civilisation vieillissante fait coexister dans ce roman les intuitions poétiques, les effets comiques, une mélancolie fataliste.Ce livre est une saisissante fable politique et morale.'

Now i will create a cleaning script based on my experimentation.

Next i will check that all the images are working as intended

In [21]:
from PIL import Image
df = pd.read_csv("../data/processed/books_clean.csv") # Processed CSV -> DataFrame
img = Image.open("../data/raw/" + df.loc[0, "image_path"]) # Open the image file for the first book
print(img.size) # Show the size of the image (width, height)
print(img.format) # Show the format of the image (JPEG, PNG, etc.)
print(img.mode) # Show the mode of the image (RGB, RGBA, etc.)
print(img.verify()) # Verify that the image is not corrupted (returns None if the image is valid)

(235, 362)
JPEG
RGB
None

From my previous cell i will write code that loops through all the books and checks that no images are corrupted

In [25]:
index = 1
for path in df["image_path"]:
    img = Image.open("../data/raw/" + path)
    if img.verify() is None:
        print(f"{index}. {path} is valid.")
    else:
        print(f"{index}. {path} is invalid.")
        print(f"Error: {img.verify()}")
    index += 1

1. images/soumission_998.jpg is valid.
2. images/private-paris-private-10_958.jpg is valid.
3. images/we-love-you-charlie-freeman_954.jpg is valid.
4. images/thirst_946.jpg is valid.
5. images/the-murder-that-never-was-forensic-instincts-5_939.jpg is valid.
6. images/tuesday-nights-in-1980_870.jpg is valid.
7. images/the-vacationers_863.jpg is valid.
8. images/the-regional-office-is-under-attack_858.jpg is valid.
9. images/finders-keepers-bill-hodges-trilogy-2_807.jpg is valid.
10. images/the-time-keeper_766.jpg is valid.
11. images/the-testament-of-mary_765.jpg is valid.
12. images/the-first-hostage-jb-collins-2_749.jpg is valid.
13. images/take-me-with-you_741.jpg is valid.
14. images/still-life-with-bread-crumbs_738.jpg is valid.
15. images/shtum_733.jpg is valid.
16. images/my-name-is-lucy-barton_720.jpg is valid.
17. images/my-mrs-brown_719.jpg is valid.
18. images/mr-mercedes-bill-hodges-trilogy-1_717.jpg is valid.
19. images/i-am-pilgrim-pilgrim-1_703.jpg is valid.
20. images/eligible-the-austen-project-4_692.jpg is valid.
21. images/eight-hundred-grapes_690.jpg is valid.
22. images/dear-mr-knightley_684.jpg is valid.
23. images/cometh-the-hour-the-clifton-chronicles-6_681.jpg is valid.
24. images/balloon-animals_665.jpg is valid.
25. images/a-man-called-ove_653.jpg is valid.
26. images/the-silent-sister-riley-macpherson-1_641.jpg is valid.
27. images/the-dinner-party_635.jpg is valid.
28. images/the-improbability-of-love_607.jpg is valid.
29. images/mothering-sunday_600.jpg is valid.
30. images/lies-and-other-acts-of-love_596.jpg is valid.
31. images/daredevils_590.jpg is valid.
32. images/112263_583.jpg is valid.
33. images/the-shack_576.jpg is valid.
34. images/the-high-mountains-of-portugal_547.jpg is valid.
35. images/millers-valley_534.jpg is valid.
36. images/hystopia-a-novel_523.jpg is valid.
37. images/the-bourne-identity-jason-bourne-1_492.jpg is valid.
38. images/sister-dear_485.jpg is valid.
39. images/memoirs-of-a-geisha_477.jpg is valid.
40. images/me-before-you-me-before-you-1_434.jpg is valid.
41. images/deception-point_426.jpg is valid.
42. images/the-little-paris-bookshop_407.jpg is valid.
43. images/the-firm_404.jpg is valid.
44. images/the-expatriates_401.jpg is valid.
45. images/siddhartha_393.jpg is valid.
46. images/last-one-home-new-beginnings-1_383.jpg is valid.
47. images/digital-fortress_369.jpg is valid.
48. images/atlas-shrugged_314.jpg is valid.
49. images/three-martini-lunch_290.jpg is valid.
50. images/the-nightingale_267.jpg is valid.
51. images/the-infinities_257.jpg is valid.
52. images/the-husbands-secret_256.jpg is valid.
53. images/the-da-vinci-code-robert-langdon-2_240.jpg is valid.
54. images/the-art-of-fielding_228.jpg is valid.
55. images/lila-gilead-3_190.jpg is valid.
56. images/jurassic-park-jurassic-park-1_180.jpg is valid.
57. images/inferno-robert-langdon-4_176.jpg is valid.
58. images/crazy-rich-asians-crazy-rich-asians-1_143.jpg is valid.
59. images/big-little-lies_129.jpg is valid.
60. images/the-course-of-love_109.jpg is valid.
61. images/when-im-gone_95.jpg is valid.
62. images/the-silent-wife_83.jpg is valid.
63. images/the-bette-davis-club_59.jpg is valid.
64. images/kitchens-of-the-great-midwest_28.jpg is valid.
65. images/bright-lines_11.jpg is valid.
66. images/worlds-elsewhere-journeys-around-shakespeares-globe_972.jpg is valid.
67. images/the-five-love-languages-how-to-express-heartfelt-commitment-to-your-mate_969.jpg is valid.
68. images/reasons-to-stay-alive_959.jpg is valid.
69. images/higherselfie-wake-up-your-life-free-your-soul-find-your-tribe_957.jpg is valid.
70. images/unseen-city-the-majesty-of-pigeons-the-discreet-charm-of-snails-other-wonders-of-the-urban-wilderness_952.jpg is valid.
71. images/throwing-rocks-at-the-google-bus-how-growth-became-the-enemy-of-prosperity_948.jpg is valid.
72. images/the-life-changing-magic-of-tidying-up-the-japanese-art-of-decluttering-and-organizing_936.jpg is valid.
73. images/the-gutsy-girl-escapades-for-your-life-of-epic-adventure_934.jpg is valid.
74. images/the-electric-pencil-drawings-from-inside-state-hospital-no-3_933.jpg is valid.
75. images/spark-joy-an-illustrated-master-class-on-the-art-of-organizing-and-tidying-up_927.jpg is valid.
76. images/reskilling-america-learning-to-labor-in-the-twenty-first-century_922.jpg is valid.
77. images/in-the-country-we-love-my-family-divided_901.jpg is valid.
78. images/everydata-the-misinformation-hidden-in-the-little-data-you-consume-every-day_891.jpg is valid.
79. images/call-the-nurse-true-stories-of-a-country-nurse-on-a-scottish-isle_885.jpg is valid.
80. images/algorithms-to-live-by-the-computer-science-of-human-decisions_880.jpg is valid.
81. images/the-power-of-now-a-guide-to-spiritual-enlightenment_855.jpg is valid.
82. images/the-omnivores-dilemma-a-natural-history-of-four-meals_854.jpg is valid.
83. images/the-genius-of-birds_843.jpg is valid.
84. images/the-artists-way-a-spiritual-path-to-higher-creativity_839.jpg is valid.
85. images/so-youve-been-publicly-shamed_832.jpg is valid.
86. images/daring-greatly-how-the-courage-to-be-vulnerable-transforms-the-way-we-live-love-parent-and-lead_799.jpg is valid.
87. images/big-magic-creative-living-beyond-fear_796.jpg is valid.
88. images/becoming-wise-an-inquiry-into-the-mystery-and-art-of-living_795.jpg is valid.
89. images/agnostic-a-spirited-manifesto_786.jpg is valid.
90. images/whole-lotta-creativity-going-on-60-fun-and-unusual-exercises-to-awaken-and-strengthen-your-creativity_780.jpg is valid.
91. images/whats-it-like-in-space-stories-from-astronauts-whove-been-there_779.jpg is valid.
92. images/the-year-of-magical-thinking_770.jpg is valid.
93. images/the-literature-book-big-ideas-simply-explained_755.jpg is valid.
94. images/the-bad-ass-librarians-of-timbuktu-and-their-race-to-save-the-worlds-most-precious-manuscripts_745.jpg is valid.
95. images/swell-a-year-of-waves_740.jpg is valid.
96. images/no-dream-is-too-high-life-lessons-from-a-man-who-walked-on-the-moon_722.jpg is valid.
97. images/looking-for-lovely-collecting-the-moments-that-matter_710.jpg is valid.
98. images/let-it-out-a-journey-through-journaling_708.jpg is valid.
99. images/hamilton-the-revolution_699.jpg is valid.
100. images/far-away-places-on-the-brink-of-change-seven-continents-twenty-five-years_694.jpg is valid.
101. images/eaternity-more-than-150-deliciously-easy-vegan-recipes-for-a-long-healthy-satisfied-joyful-life_689.jpg is valid.
102. images/buying-in-the-secret-dialogue-between-what-we-buy-and-who-we-are_670.jpg is valid.
103. images/brain-on-fire-my-month-of-madness_669.jpg is valid.
104. images/abstract-city_658.jpg is valid.
105. images/13-hours-the-inside-account-of-what-really-happened-in-benghazi_645.jpg is valid.
106. images/the-lonely-city-adventures-in-the-art-of-being-alone_639.jpg is valid.
107. images/the-diary-of-a-young-girl_634.jpg is valid.
108. images/snatched-how-a-drug-queen-went-undercover-for-the-dea-and-was-kidnapped-by-colombian-guerillas_631.jpg is valid.
109. images/furiously-happy-a-funny-book-about-horrible-things_619.jpg is valid.
110. images/the-sleep-revolution-transforming-your-life-one-night-at-a-time_608.jpg is valid.
111. images/mother-can-you-not_599.jpg is valid.
112. images/a-mothers-reckoning-living-in-the-aftermath-of-tragedy_585.jpg is valid.
113. images/10-happier-how-i-tamed-the-voice-in-my-head-reduced-stress-without-losing-my-edge-and-found-self-help-that-actually-works_582.jpg is valid.
114. images/chernobyl-012340-the-incredible-true-story-of-the-worlds-worst-nuclear-disaster_560.jpg is valid.
115. images/zero-to-one-notes-on-startups-or-how-to-build-the-future_555.jpg is valid.
116. images/why-not-me_554.jpg is valid.
117. images/when-breath-becomes-air_553.jpg is valid.
118. images/the-midnight-assassin-panic-scandal-and-the-hunt-for-americas-first-serial-killer_549.jpg is valid.
119. images/smarter-faster-better-the-secrets-of-being-productive-in-life-and-business_543.jpg is valid.
120. images/rising-strong_539.jpg is valid.
121. images/mans-search-for-meaning_533.jpg is valid.
122. images/love-that-boy-what-two-presidents-eight-road-trips-and-my-son-taught-me-about-a-parents-expectations_532.jpg is valid.
123. images/living-forward-a-proven-plan-to-stop-drifting-and-get-the-life-you-want_531.jpg is valid.
124. images/i-will-find-you_524.jpg is valid.
125. images/brazen-the-courage-to-find-the-you-thats-been-hiding_514.jpg is valid.
126. images/between-the-world-and-me_513.jpg is valid.
127. images/being-mortal-medicine-and-what-matters-in-the-end_512.jpg is valid.
128. images/a-murder-over-a-girl-justice-gender-junior-high_511.jpg is valid.
129. images/for-the-love-fighting-for-grace-in-a-world-of-impossible-standards_467.jpg is valid.
130. images/finding-god-in-the-ruins-how-god-redeems-pain_466.jpg is valid.
131. images/the-man-who-mistook-his-wife-for-a-hat-and-other-clinical-tales_451.jpg is valid.
132. images/in-cold-blood_432.jpg is valid.
133. images/girl-interrupted_429.jpg is valid.
134. images/why-save-the-bankers-and-other-essays-on-our-economic-and-political-crisis_418.jpg is valid.
135. images/talking-to-girls-about-duran-duran-one-young-mans-quest-for-true-love-and-a-cooler-haircut_394.jpg is valid.
136. images/my-mother-was-nuts_388.jpg is valid.
137. images/data-a-love-story-how-i-gamed-online-dating-to-meet-my-match_367.jpg is valid.
138. images/the-jazz-of-physics-the-secret-link-between-music-and-the-structure-of-the-universe_350.jpg is valid.
139. images/the-gunning-of-america-business-and-the-making-of-american-gun-culture_347.jpg is valid.
140. images/the-geography-of-bliss-one-grumps-search-for-the-happiest-places-in-the-world_346.jpg is valid.
141. images/god-is-not-great-how-religion-poisons-everything_323.jpg is valid.
142. images/we-the-people-the-modern-day-figures-who-have-reshaped-and-affirmed-the-founding-fathers-vision-of-america_302.jpg is valid.
143. images/very-good-lives-the-fringe-benefits-of-failure-and-the-importance-of-imagination_298.jpg is valid.
144. images/unstuffed-decluttering-your-home-mind-and-soul_296.jpg is valid.
145. images/under-the-banner-of-heaven-a-story-of-violent-faith_295.jpg is valid.
146. images/trespassing-across-america-one-mans-epic-never-done-before-and-sort-of-illegal-hike-across-the-heartland_291.jpg is valid.
147. images/the-name-of-god-is-mercy_264.jpg is valid.
148. images/stiff-the-curious-lives-of-human-cadavers_226.jpg is valid.
149. images/spilled-milk-based-on-a-true-story_225.jpg is valid.
150. images/rise-of-the-rocket-girls-the-women-who-propelled-us-from-missiles-to-the-moon-to-mars_213.jpg is valid.
151. images/outliers-the-story-of-success_204.jpg is valid.
152. images/notes-from-a-small-island-notes-from-a-small-island-1_200.jpg is valid.
153. images/night-the-night-trilogy-1_199.jpg is valid.
154. images/miracles-from-heaven-a-little-girl-her-journey-to-heaven-and-her-amazing-story-of-healing_195.jpg is valid.
155. images/letter-to-a-christian-nation_186.jpg is valid.
156. images/lets-pretend-this-never-happened-a-mostly-true-memoir_185.jpg is valid.
157. images/its-never-too-late-to-begin-again-discovering-creativity-and-meaning-at-midlife-and-beyond_179.jpg is valid.
158. images/into-the-wild_177.jpg is valid.
159. images/in-the-garden-of-beasts-love-terror-and-an-american-family-in-hitlers-berlin_175.jpg is valid.
160. images/i-am-malala-the-girl-who-stood-up-for-education-and-was-shot-by-the-taliban_172.jpg is valid.
161. images/gratitude_163.jpg is valid.
162. images/disrupted-my-misadventure-in-the-start-up-bubble_148.jpg is valid.
163. images/brave-enough_135.jpg is valid.
164. images/born-to-run-a-hidden-tribe-superathletes-and-the-greatest-race-the-world-has-never-seen_133.jpg is valid.
165. images/blink-the-power-of-thinking-without-thinking_132.jpg is valid.
166. images/black-flags-the-rise-of-isis_131.jpg is valid.
167. images/are-we-smart-enough-to-know-how-smart-animals-are_121.jpg is valid.
168. images/a-walk-in-the-woods-rediscovering-america-on-the-appalachian-trail_118.jpg is valid.
169. images/the-suffragettes-little-black-classics-96_112.jpg is valid.
170. images/kindle-paperwhite-users-guide_103.jpg is valid.
171. images/h-is-for-hawk_102.jpg is valid.
172. images/travels-with-charley-in-search-of-america_90.jpg is valid.
173. images/the-tumor_85.jpg is valid.
174. images/the-end-of-the-jesus-era-an-investigation-1_64.jpg is valid.
175. images/eat-pray-love_16.jpg is valid.

In [26]:
index = 1
for path in df["image_path"]:
    img = Image.open("../data/raw/" + path)
    if img.verify() is not None:
        print(f"{index}. {path} is invalid.")
        print(f"Error: {img.verify()}")
    index += 1
    
print("Done")

Done

Next im going to use img.load() instead since .verrify() only catchers corruptions

In [27]:
broken = []
for path in df["image_path"]:
    try:
        with Image.open("../data/raw/" + path) as img:
            img.load()
    except Exception as e:
        broken.append(path)
        print(f"{path} is broken: {e}")

print(f"{len(broken)} broken images out of {len(df)}")

0 broken images out of 175

The final cleaning i want to do is to remove the non english books. To do this im going to use common english words and compare how many times they appear in the desciption.

In [32]:
ENGLISH_WORDS = {"the", "and", "or", "but", "in", "on", "at", "to", "for", "of", "with", "by"}

def english_score(text):
    words = text.lower().split()
    english_count = sum(1 for word in words if word in ENGLISH_WORDS)
    return english_count / len(words) if words else 0

print(english_score(df["description"].iloc[1]))  # Should return a score based on the number of English words

0.15447154471544716

Now i need to decide a score that catches all the foreign books but leaves out the english ones

In [33]:
for description in df["description"]:
    score = english_score(description)
    if score < 0.1:  # Arbitrary threshold for low English content
        print(f"Low English content: {description[:50]}... (score: {score})")

Low English content: Dans une France assez proche de la nôtre, un homme... (score: 0.0)
Low English content: Who is Jason Bourne? Is he an assassin, a terroris... (score: 0.08695652173913043)
Low English content: Forty million people date online each year. Most d... (score: 0.06896551724137931)
Low English content: Kindle Paperwhite User's Guide... (score: 0.0)

Looking at the descriptions i got only one of them is foreign. Because of this im not going to drop it. Since it is only one book it should be fine to leave it. I can still use the image from it so that is why im going to keep it.

##EXPLORATION

In [34]:
df = pd.read_csv("../data/processed/books_clean.csv")

1. What are the proportions between the categories?

In [39]:
print(df["category"].value_counts(normalize=True))  # Show the proportion between the categories

category
Nonfiction    0.628571
Fiction       0.371429
Name: proportion, dtype: float64

1. 63% of the books are nonfiction. So a model that always guessses Nonfiction is right 63% of the time

2.  Is there any deviations in Title length and description length between the categories?

In [40]:
df["description_words"] = df["description"].str.split().str.len()  # Count the number of words in each description
print(df["description_words"].describe())  # Show statistics about the number of words in each description
df["title_words"] = df["title"].str.split().str.len()  # Count the number of words in each title
print(df["title_words"].describe())  # Show statistics about the number of words in each title

count    175.000000
mean     199.931429
std       93.794933
min        4.000000
25%      147.000000
50%      190.000000
75%      237.000000
max      746.000000
Name: description_words, dtype: float64
count    175.000000
mean       7.291429
std        4.717379
min        1.000000
25%        4.000000
50%        6.000000
75%       11.000000
max       22.000000
Name: title_words, dtype: float64

In [ ]:
#Now i will compare the categories against each other

df.groupby("category")[["description_words", "title_words"]].describe()  # Show statistics for each category

           description_words                                               \
                       count        mean         std   min     25%    50%
category
Fiction                 65.0  180.307692   62.023666  68.0  147.00  173.0
Nonfiction             110.0  211.527273  106.862572   4.0  144.75  201.5

                         title_words                                      \
              75%    max       count      mean       std  min   25%  50%
category
Fiction     212.0  368.0        65.0  3.707692  1.817649  1.0  2.00  4.0
Nonfiction  254.5  746.0       110.0  9.409091  4.626004  1.0  5.25  9.0


             75%   max
category
Fiction      5.0   8.0
Nonfiction  13.0  22.0

2. The description lengths are a weak signal since they have a lot of overlap. The difference in mean words mostly comes from the extremes in Nonficrtion.
However title words have barely any overlap. Looking at both categories ranges we see that fictions top quartile ends where nonfictions start.

In [44]:
df.groupby("category").sample(10, random_state=1)[["title","description"]]

,title,description
51,The Husband's Secret,At the heart of The Husband’s Secret is a lett...
55,Jurassic Park (Jurassic Park #1),A billionaire has created a technique to clone...
46,Digital Fortress,"Before the multi-million, runaway bestseller T..."
2,"We Love You, Charlie Freeman","The Freeman family--Charles, Laurel, and their..."
47,Atlas Shrugged,This is the story of a man who said that he wo...
53,The Art of Fielding,"At Westish College, a small school on the shor..."
21,Dear Mr. Knightley,Dear Mr. Knightley is a contemporary epistolar...
26,The Dinner Party,This Passover Seder is not just any Passover S...
44,Siddhartha,"In the novel, Siddhartha, a young man, leaves ..."
40,Deception Point,When a new NASA satellite spots evidence of an...
109,"The Sleep Revolution: Transforming Your Life, ...",We are in the midst of a sleep deprivation cri...
112,"10% Happier: How I Tamed the Voice in My Head,...",After having a nationally televised panic atta...
128,For the Love: Fighting for Grace in a World of...,"The popular writer, blogger, and television pe..."
131,In Cold Blood,"On November 15, 1959, in the small town of Hol..."
151,Notes from a Small Island (Notes From a Small ...,"""Suddenly, in the space of a moment, I realize..."
76,In the Country We Love: My Family Divided,The star of Orange is the New Black and Jane t...
143,"Unstuffed: Decluttering Your Home, Mind, and Soul",STUFF. It's everywhere. Lurking in corners and...
100,Eaternity: More than 150 Deliciously Easy Vega...,Vegan chef and wellness expert Jason Wrobel of...
164,Blink: The Power of Thinking Without Thinking,"In his landmark bestseller The Tipping Point, ..."
79,Algorithms to Live By: The Computer Science of...,A fascinating exploration of how insights from...

In [45]:
#The titles gets cut off
pd.set_option('display.max_colwidth', None)  # Set max column width to None to display full content

In [50]:
df.groupby("category").sample(10, random_state=2)[["title"]]

                                                                                                         title
0                                                                                                   Soumission
28                                                                                            Mothering Sunday
62                                                                                        The Bette Davis Club
29                                                                                 Lies and Other Acts of Love
23                                                                                             Balloon Animals
10                                                                                       The Testament of Mary
30                                                                                                  Daredevils
51                                                                                        The Husband's Secret
36                                                                       The Bourne Identity (Jason Bourne #1)
32                                                                                                   The Shack
107            Snatched: How A Drug Queen Went Undercover for the DEA and Was Kidnapped By Colombian Guerillas
88                                                                              Agnostic: A Spirited Manifesto
110                                                                                       Mother, Can You Not?
113                        Chernobyl 01:23:40: The Incredible True Story of the World's Worst Nuclear Disaster
78                                          Call the Nurse: True Stories of a Country Nurse on a Scottish Isle
68                                          #HigherSelfie: Wake Up Your Life. Free Your Soul. Find Your Tribe.
71                      The Life-Changing Magic of Tidying Up: The Japanese Art of Decluttering and Organizing
69   Unseen City: The Majesty of Pigeons, the Discreet Charm of Snails & Other Wonders of the Urban Wilderness
130                                            The Man Who Mistook His Wife for a Hat and Other Clinical Tales
165                                                                              Black Flags: The Rise of ISIS

In [51]:
df["has_#"] = df["title"].str.contains("#")
df.groupby("category")[["has_#"]].mean()  # Show the proportion of titles containing "#" for each category

               has_#
category
Fiction     0.261538
Nonfiction  0.045455

I noticed that a lot of the Fiction titles contained #. This is a series marker, fiction books are often parts of series. # is usually followed up by numbers so lets check for that instead to make it more specific

In [54]:
df["has_#"] = df["title"].str.contains(r"#\d")
df.groupby("category")[["has_#"]].mean()  # Show the proportion of titles containing "#" followed by digits for each category

               has_#
category
Fiction     0.261538
Nonfiction  0.036364

In [55]:
df[(df["category"] == "Nonfiction") & df["has_#"]][["title"]]

                                                        title
151  Notes from a Small Island (Notes From a Small Island #1)
152                              Night (The Night Trilogy #1)
168             The Suffragettes (Little Black Classics, #96)
173            The End of the Jesus Era (An Investigation #1)

Some non-fiction titles also contain a series marker. But i still think this is useful data.

Next i want to examine which titles contain :

In [56]:
df["has_:"] = df["title"].str.contains(":")
df.groupby("category")[["has_:"]].mean()  # Show the proportion of titles containing ":" for each category

               has_:
category
Fiction     0.015385
Nonfiction  0.709091

In [57]:
df[(df["category"] == "Fiction") & df["has_:"]][["title"]]

                title
35  Hystopia: A Novel

There is only one fiction book that contains :